import csv
import random

# Define categories and issues
categories = {
    "Cleanliness Issue": [
        "The station floors are sticky and dirty.",
        "There are overflowing garbage bins everywhere.",
        "Trash is scattered around the waiting area.",
        "The floors of the restrooms are frequently wet and dirty.",
        "The station's waiting area smells of mildew.",
        "The benches are covered in grime.",
        "Piles of dust are accumulating in corners.",
        "The walls are stained and unclean.",
        "There is a bad odor near the entrance.",
        "The air vents are clogged with dirt.",
        "The station's seating area is covered in spilled food and drink.",
        "There is mold growing on the walls in several areas.",
        "The trash cans are always overflowing.",
        "There is a persistent smell of urine in the restrooms.",
        "Dirty tissues and napkins are scattered around the station.",
        "The floors have not been cleaned in days.",
        "The windows are smeared with fingerprints and dirt.",
        "There are stains on the upholstery of the waiting area seats.",
        "The station's floor tiles are cracked and grimy.",
        "Insects are visible near the trash bins.",
        "The station walls have peeling paint.",
        "The carpets in the waiting area are stained and matted.",
        "There are unpleasant smells coming from the air conditioning vents.",
        "The trash in the restrooms is not being emptied regularly.",
        "Food wrappers and litter are strewn across the platforms.",
        "The public seating areas are covered in crumbs.",
        "The glass doors and windows are dirty and unwashed.",
        "The area around the ticket counters is cluttered with trash.",
        "Old newspapers and discarded items are littered in the corners.",
        "There is a buildup of grime on the escalator handrails.",
        "The floor tiles are slippery with spilled liquids.",
        "The trash collection bins are not being sanitized.",
        "The station's exterior has graffiti and dirt.",
        "The waiting area has unpleasant odors from mold.",
        "The station's ventilation system is dirty and needs cleaning.",
        "There are stains on the station walls from spills.",
        "The restrooms are infested with flies and other pests.",
        "The floors are littered with spilled food and drink.",
        "There is an accumulation of dust on ceiling fans.",
        "The station has a general appearance of neglect and dirt.",
        "The station is infested with rodents and insects.",
        "The walls of the station have visible water stains.",
        "The station's floors are sticky and attract dirt.",
        "The restrooms are in need of urgent cleaning."
    ],
    "Delay/Cancellation": [
        "Trains are frequently delayed without notice.",
        "There is no clear information on train schedules.",
        "Unexpected train cancellations cause major inconvenience.",
        "There are frequent schedule changes without updates.",
        "Trains are running behind schedule due to technical issues.",
        "Announcements about delays are often unclear.",
        "The platform displays incorrect departure times.",
        "There is no visible reason for train delays.",
        "Delays are not communicated to passengers timely.",
        "Frequent disruptions to service during peak hours.",
        "Train departure times are frequently rescheduled without notice.",
        "Passengers are not informed about train delays in advance.",
        "There are unexpected delays due to weather conditions.",
        "Train schedules are frequently updated without clear notices.",
        "The train service is inconsistent during holidays.",
        "Delayed trains often have no explanation provided.",
        "Announcements about cancellations are made too late.",
        "The train schedule is not synchronized with other services.",
        "Train services are frequently interrupted for maintenance.",
        "The platform lacks updated delay information.",
        "Trains are delayed due to staffing shortages.",
        "There is a lack of real-time updates about train statuses.",
        "Rescheduled trains are often not communicated clearly.",
        "Delays are frequently caused by signal issues.",
        "Train schedules are inconsistent and unreliable.",
        "There is no system in place for notifying passengers of changes.",
        "The delay announcements are often inaccurate.",
        "Train cancellations are frequent during peak seasons.",
        "The delay communication system is outdated.",
        "Train departures are often delayed by external factors.",
        "There is no proper protocol for handling significant delays.",
        "The platform lacks sufficient information about delays.",
        "There is frequent confusion about train arrival times.",
        "Train services are often disrupted due to construction.",
        "There are frequent delays due to technical difficulties.",
        "Announcements about train status are often missed.",
        "The station does not provide adequate support during delays.",
        "Passengers are left waiting without clear updates.",
        "Train delays cause significant inconvenience to travelers.",
        "There is no effective system for managing train cancellations.",
        "Delays are often caused by poor coordination between services.",
        "The station's delay management system needs improvement.",
        "Train delays are poorly managed and communicated.",
        "There are frequent issues with train scheduling accuracy.",
        "Trains are often delayed due to operational inefficiencies.",
        "The station does not handle delays effectively."
    ],
    "Ticket Issue": [
        "Long queues at the ticketing counter are common.",
        "The ticket machines are often out of order.",
        "Tickets are often sold out during peak times.",
        "Online ticket booking is frequently down.",
        "The ticket counter staff are slow and inefficient.",
        "There are frequent issues with ticket refunds.",
        "The automated ticket machines are confusing to use.",
        "Misplaced or lost tickets are not handled well.",
        "Errors in ticket pricing occur often.",
        "There is a lack of clear information about ticket prices.",
        "The ticketing system frequently fails to process payments.",
        "There are discrepancies between online and in-person ticket prices.",
        "Ticketing counters do not accept all forms of payment.",
        "The ticketing process is slow and cumbersome.",
        "There is no assistance for navigating the ticketing machines.",
        "Online tickets are often not synced with the station's system.",
        "The process for changing or canceling tickets is unclear.",
        "There are frequent system outages affecting ticket sales.",
        "Manual ticket issuance takes too long and is inefficient.",
        "Customers face difficulties in getting assistance with ticketing issues.",
        "Ticket counters often run out of paper for printing tickets.",
        "There are frequent technical problems with online bookings.",
        "The ticketing system fails during peak hours.",
        "The ticketing staff are unhelpful and untrained.",
        "The ticketing machines frequently mischarge customers.",
        "The ticketing process is not user-friendly.",
        "There are frequent discrepancies in ticket availability.",
        "The ticket counters are often understaffed during rush hours.",
        "The online ticket booking interface is not intuitive.",
        "There are frequent issues with the mobile ticketing app.",
        "The ticketing system does not provide clear error messages.",
        "Customers are often overcharged for tickets.",
        "Refund processes are slow and inefficient.",
        "There is a lack of transparency in ticket pricing.",
        "The ticketing machines are frequently out of service.",
        "The ticketing counters do not provide adequate customer support.",
        "There are frequent errors in ticket reservations.",
        "The ticketing process is frequently interrupted by system errors.",
        "Ticket machines often reject valid payment methods.",
        "The ticketing counters lack proper signage and information.",
        "There is no clear procedure for handling ticket disputes.",
        "The online booking system frequently crashes.",
        "The ticketing counter staff are not trained to handle issues effectively.",
        "There are frequent issues with validating tickets at entry points.",
        "The ticketing system is outdated and inefficient.",
        "There are often long waits to get ticketing issues resolved."
    ],
    "Staff Behavior": [
        "Some staff members are rude and unhelpful.",
        "Staff do not enforce rules about eating or drinking.",
        "Customer service at the ticketing counter is slow.",
        "Staff members are frequently absent or unavailable.",
        "The staff are not knowledgeable about train schedules.",
        "There is a lack of courtesy from security personnel.",
        "Staff often ignore passenger complaints.",
        "Assistance for disabled passengers is insufficient.",
        "Staff do not address cleanliness issues promptly.",
        "The behavior of staff towards passengers is unprofessional.",
        "Staff are often seen arguing with passengers.",
        "There is a lack of respect from staff towards travelers.",
        "Staff members are frequently engaged in personal conversations.",
        "The behavior of the staff at the information desk is unhelpful.",
        "Staff do not provide adequate information about delays.",
        "The staff's appearance is often unkempt.",
        "There is a lack of accountability among station staff.",
        "Staff members are frequently unavailable for assistance.",
        "Staff do not follow proper procedures for handling complaints.",
        "The staff exhibit a lack of empathy towards distressed passengers.",
        "Some staff members display a lack of professionalism.",
        "Staff are often inattentive to passenger needs.",
        "Security staff are often unresponsive to concerns.",
        "The staff are not proactive in assisting passengers.",
        "There is a general lack of politeness among staff.",
        "Staff members frequently ignore service protocols.",
        "The attitude of the staff is often dismissive.",
        "Staff do not provide clear instructions during emergencies.",
        "The staff's interactions with passengers are often curt.",
        "Staff frequently fail to address customer issues effectively.",
        "There is a lack of customer-focused behavior from staff.",
        "Staff members are often seen using their phones during work.",
        "There is frequent miscommunication between staff and passengers.",
        "Staff are not trained to handle difficult situations.",
        "The behavior of the staff is inconsistent and unprofessional.",
        "Staff frequently fail to acknowledge or greet passengers.",
        "The staff's service is often slow and inefficient.",
        "There is a lack of attentiveness from customer service staff.",
        "Staff members often appear uninterested in their duties.",
        "Security personnel are frequently seen ignoring safety protocols.",
        "The staff's responses to passenger inquiries are often inadequate.",
        "Staff members often seem disinterested in solving problems.",
        "There is frequent lack of engagement from station staff.",
        "The attitude of the staff affects overall passenger experience."
    ],
    "Comfort Issue": [
        "The seats in the train are worn out and uncomfortable.",
        "Air conditioning on the train is not functioning properly.",
        "The lighting on the train is too dim.",
        "There is no proper ventilation in the train compartments.",
        "The noise level inside the train is excessive.",
        "Seats are too close together, causing discomfort.",
        "The temperature inside the train is inconsistent.",
        "The train's interior is poorly maintained.",
        "There is insufficient legroom on the train.",
        "The train lacks adequate padding on the seats.",
        "The air conditioning is either too cold or too warm.",
        "The train's heating system is not functioning properly.",
        "There are uncomfortable vibrations during travel.",
        "The train seats are too narrow for average-sized passengers.",
        "There is excessive air draft in the compartments.",
        "The train windows are fogged up, affecting visibility.",
        "There is a lack of reclining options on the seats.",
        "The overhead storage compartments are too low.",
        "The train seats are frequently stained and dirty.",
        "The ride quality is rough and uncomfortable.",
        "The train's suspension system is inadequate.",
        "There is a lack of cleanliness in the seating areas.",
        "The train's interior temperature is not adjustable.",
        "The seats are not ergonomically designed.",
        "There are no amenities to enhance passenger comfort.",
        "The train's interior lighting is harsh and uncomfortable.",
        "The compartments are overcrowded and cramped.",
        "The noise from the train's engines is disruptive.",
        "There is a lack of privacy in the seating areas.",
        "The train's ventilation system is ineffective.",
        "The seating is not suitable for long journeys.",
        "The train's climate control system is malfunctioning.",
        "The seats lack proper support for long periods of sitting.",
        "There are frequent issues with the train's air quality.",
        "The seating areas do not provide adequate cushioning.",
        "The train's ride quality is affected by poor maintenance.",
        "The compartments are not properly insulated.",
        "The seating arrangement is not well planned.",
        "There are no adjustable features on the seats.",
        "The train lacks adequate facilities for passengers with special needs.",
        "The comfort of the train seats is subpar.",
        "The train's noise levels are consistently high.",
        "The seating area is often too hot or too cold.",
        "The train's climate control is not user-friendly.",
        "The ride is frequently uncomfortable due to poor suspension."
    ],
    "Luggage Issue": [
        "There is inadequate space for luggage on the train.",
        "There are no designated areas for storing large bags.",
        "There is no clear signage for luggage storage.",
        "Luggage storage areas are frequently full.",
        "The luggage racks are broken or missing.",
        "There is no assistance available for handling large luggage.",
        "Luggage storage areas are poorly lit and inconvenient.",
        "The size limits for luggage are not clearly stated.",
        "There is no security for stored luggage.",
        "Passengers often have to store luggage in aisles.",
        "The luggage compartments are too small for larger bags.",
        "There is insufficient signage for luggage storage areas.",
        "Luggage storage areas are not easily accessible.",
        "The racks for luggage are not sturdy or reliable.",
        "There is no proper system for storing valuable items.",
        "Luggage storage is not adequately monitored for security.",
        "There are frequent conflicts over luggage space.",
        "The luggage handling process is disorganized.",
        "There is no clear policy for oversized luggage.",
        "Passengers struggle to find available luggage space.",
        "The luggage compartments are not well maintained.",
        "There is insufficient room for storing additional bags.",
        "The luggage storage areas are often overcrowded.",
        "Luggage storage is frequently blocked or obstructed.",
        "There is no clear system for luggage allocation.",
        "The luggage handling system is outdated.",
        "The luggage compartments do not fit modern luggage sizes.",
        "The storage areas are not designed for easy access.",
        "The luggage racks are often too high to reach.",
        "There is no assistance for passengers with bulky luggage.",
        "The luggage compartments are poorly designed.",
        "There is frequent confusion over luggage placement.",
        "The storage areas are often poorly organized.",
        "There are frequent issues with securing luggage.",
        "The luggage compartments lack proper ventilation.",
        "The luggage handling procedures are not well communicated.",
        "There are no clear guidelines for luggage placement.",
        "The luggage racks are not cleaned regularly.",
        "The luggage storage process is inefficient.",
        "There is a lack of space for personal items.",
        "The luggage storage areas are often dirty.",
        "The luggage compartments are not secure.",
        "There is no proper system for managing oversized bags.",
        "The luggage storage facilities are frequently inadequate.",
        "The handling of luggage is often slow and disorganized."
    ]
}



# Generate data
num_entries = 500
data = []

for _ in range(num_entries):
    issue_type = random.choice(list(categories.keys()))
    description = random.choice(categories[issue_type])
    data.append([issue_type, description])

# Write to CSV
with open('extra.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["Category", "Text"])
    writer.writerows(data)

print("CSV file has been created.")
